# Generated by Django 4.1.6 on 2023-02-18 05:40

import account.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(help_text='Username should be unique', max_length=32, unique=True, verbose_name='Username')),
                ('email', models.EmailField(help_text='Email should be unique', max_length=32, unique=True, verbose_name='Email')),
                ('photo', models.ImageField(blank=True, upload_to=account.models.username_photo_path, verbose_name='Change account photo')),
                ('city', models.CharField(max_length=64)),
                ('country', models.CharField(max_length=64)),
                ('changed_username', models.DateTimeField(default=django.utils.timezone.now, help_text='Username can be changed every 24 hours', verbose_name='Changed username date')),
                ('moderator_id', models.IntegerField(blank=True, null=True)),
                ('is_moderator', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
