# Generated by Django 4.1.6 on 2023-02-18 05:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateTimeField(auto_now_add=True)),
                ('report_comment', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='report_comment', to='comment.comment')),
                ('report_from_account', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='report_from_set', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
