# Generated by Django 4.1.6 on 2023-02-18 05:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=516)),
                ('published_date', models.DateTimeField(auto_now_add=True)),
                ('is_edited', models.BooleanField(default=False)),
                ('has_spoiler', models.BooleanField(default=False)),
                ('device_type', models.CharField(max_length=16)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='author_set', to=settings.AUTH_USER_MODEL)),
                ('replies', models.ManyToManyField(blank=True, related_name='replies_set', to='comment.comment')),
            ],
        ),
    ]
